###服务启动端口号
server:
  port: 8000
###服务名称(服务注册到注册中心名称)
spring:
  application:
    name: app-itmayiedu-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka,http://localhost:8200/eureka


    ###将我的服务注册到服务中心上
    register-with-eureka: true
    ###检索服务
    fetch-registry: true