###注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
###api网关端口号
server:
  port: 80
###网关名称
spring:
  application:
    name: service-zuul
###配置网关反向代理
zuul:
  routes:
    api-a:
      ### /api-member/访问转发到会员服务
      path: /api-member/**
      serviceId: app-itmayiedu-member
    api-b:
      ### /api-order/访问转发到订单服务
      path: /api-order/**
      serviceId: app-itmayiedu-order