###服务端口号
server:
  port: 8200
##定义服务名称
  spring:
    application:
    name: app-itmayidu-eureka
###eureka 基本信息配置
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
    ###集群之间相互注册
    register-with-eureka: true
    ###集群之间相互注册
    fetch-registry: true